### ISSUE TITLE
Fix vulnerabilities security

### ISSUE THREAD

**Issue by kimyvgy** [viblo-asia/organization-landing-page#14]
As the title, we have some vulnerabilities in the dependencies. I have yet to be able to fix these vulnerabilities. Could you please help us!

1. Fork this repository
2. Pull sourcecode into your local
3. Check vulnerabilities with command line:
```
# yarn
yarn audit

# npm
npm audit
```
4. Upgrade to patched dependencies & re-build this app. Please make sure that everything is working fine.
5. Open Pull Request

**Comment by vasu2001** [comment]
#15 I've submitted a pr pls review

**Comment by kimyvgy** [comment]
@vasu2001 Thank you so much. I will check it.
